import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import CalendarBar from "../modules/calendar/CalendarBar";
import MonthView from "../modules/calendar/month/MonthView";
import initNotifications from "../lib/initNotifications";
import { useGetUserEventsQuery } from "../generated/graphql";

// TODO: Find a better way for styling Main div so it grows to have 100 %
const Home: NextPage = () => {
  const [result, reexecute] = useGetUserEventsQuery({
    variables: { where: { userId: { equals: 1 } } },
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col h-screen w-screen">
        <CalendarBar />
        <MonthView />
      </div>
      <div>{result.data?.events[0].title}</div>
    </div>
  );
};

export default Home;
