import type { NextPage } from "next";
import Head from "next/head";
import Calendar from "../modules/calendar/Calendar";
import MonthView from "../modules/calendar/month/MonthView";
import Sidebar from "../modules/sidebar/Sidebar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-row relative h-full items-stretch">
        <Sidebar />
        <Calendar />
      </main>
    </div>
  );
};

export default Home;
