import type { NextPage } from "next";
import Head from "next/head";
import CalendarBar from "../modules/calendar/CalendarBar";
import EventModal from "../modules/calendar/EventModal";

import MonthView from "../modules/calendar/month/MonthView";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col">
        <CalendarBar />

        <MonthView />
      </div>
    </div>
  );
};

export default Home;
